### ISSUE TITLE
Connection with Tabular Data Package spec

### ISSUE THREAD

**Issue by rgrp** [ropensci/datapackage#28]
Wondered if you folks were aware of "Data Packages" work associated with http://data.okfn.org/ In particular, you may be interested specifically in Tabular Data Package http://data.okfn.org/doc/tabular-data-package

**Comment by mbjones** [comment]
Yes, excellent work there. I've interacted with you about this in 2013, when I pointed out other non-json packaging standards in widespread use in the sciences in your issue tracker (https://github.com/dataprotocols/dataprotocols/issues/65). We've since continued to evolve our use or BagIt and OAI-ORE specs, and now are using OAI-ORE for PROV-compatible provenance statements in our packages as well, which is why we're building out tooling support in R and Matlab for the data packaging specs.  I've also been talking with the folks at the RO (Research Objects) initiative, as their community of practice is also based on the ORE/BagIt combination.  They have a [nice table of many of the [overlapping data packaging](http://www.researchobject.org/initiative/) specifications that are in use in various communities.

I could definitely see having JSON-LD serializations of our packages, and if we head down that path we will definitely consider compatibility with your work as important. But for now, we find the ties to RDF and OWL for semantic reasoning to be really useful, and JSON-LD is just starting to catch up in that area (mostly via JSON-LD to RDF converters that allow standard reasoning engines to be applied, although maybe native JSON reasoners will emerge soon).
